# Generated by Django 2.0.4 on 2018-07-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfchatbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientNames',
        ),
    ]
