# Generated by Django 2.0.4 on 2018-07-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfchatbox', '0002_delete_patientnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
