# Generated by Django 2.0.4 on 2018-07-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfchatbox', '0004_auto_20180727_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='dfchatbox.Patient'),
        ),
    ]
