# Generated by Django 2.0.4 on 2018-07-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfchatbox', '0005_auto_20180727_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, to='dfchatbox.Patient'),
        ),
    ]
