# Generated by Django 2.0.7 on 2018-07-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfchatbox', '0006_auto_20180727_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
    ]
